# Generated by Django 5.0.2 on 2024-03-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Savings',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
