# Generated by Django 5.0.2 on 2024-03-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_userprofile_savings_alter_userprofile_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
